#!/usr/bin/env bash

set -o errexit
set -o pipefail

lint() {
  # Lint Python code
  ruff check "${@}"
}

format:imports() {
  # Sort Python imports
  lint --select I --fix "${@}"
}

format() {
  # Format Python code
  ruff format "${@}"
}

quality() {
  # Perform all code quality commands together
  format:imports "${@}"
  format
  lint
}

function test {
  # Run test suite
  python3 -m unittest discover --start-directory tests/src "${@}"
}

function ci:install-deps {
  pip3 install ruff
}

function ci:test {
  lint "${@}"
  cmd ruff check --select I
  format --check
  test "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
