name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  schedule:
    - cron: "30 12 * * *"

jobs:
  test:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v6"

      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.10"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Lint and test"
        run: |
          ./run ci:test
